---
- hosts: all
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: True
    ansible_user: cli
    ansible_password: fibranne
    ansible_become_method: enable
    ansible_become_pass: fibranne
    ansible_persistent_log_messages: True
        
        
  tasks:
  - name: configure new vlan 
    icx_vlan:
      name: test-vlan
      vlan_id: 2626
      tagged: 
        name:
        - ethernet 1/1/4 to 1/1/6
      interfaces:
        name:
          - ethernet 1/1/4
      # check_running_config: false
      # ip_dhcp_snooping: False
      # ip_arp_inspection: True
  ##########not working Error:"msg": "tagged lag 4\r\nError - invalid interface lg4\r\nSSH@ankit(config-vlan-12)#"
  ###An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Value of unknown type: <type '_sre.SRE_Match'>, <_sre.SRE_Match object at 0x7ffba40b18a0>

  # - name: purge interface parameter
  #   icx_vlan:
  #    name: test-vlan
  #    vlan_id: 2626
  #    interfaces:
  #      name:
  #        - ethernet 1/2/4
  #    state: absent
  #     #  purge: true

  ####fatal: [10.176.145.235]: FAILED! => {"changed": false, "msg": "untagged ethernet 2/1/12\r\nError - invalid module for interface 2/1/12\r\nSSH@ICX7150-48P Router(config-vlan-2626)#"}

  # - name: modify the excisting vlan with purge
  #   icx_vlan:
  #    name: test-vlan
  #    vlan_id: 12
  #    tagged: 
  #     name:
  #       - ethernet 1/1/40 to 1/1/43
  #       - ethernet 1/1/10
  #       # - lag 4
  #     purge: True
  #    interfaces:
  #     name:
  #       - ethernet 1/1/2 to 1/1/4
  #       # - lag 5 to 9
  #     purge: True
  #    ip_dhcp_snooping: False
  #    ip_arp_inspection: True
    #  state_tagged: absent
    

  # - name: enable ip_dhcp snooping
  #   icx_vlan:
  #     vlan_id: 12
  #     ip_dhcp_snooping: False
  
  
  # - name: enable ip_arp_inspection
  #   icx_vlan:
  #     vlan_id: 12
  #     ip_arp_inspection: True

  # test1
  # - name: enable STP
  #   icx_vlan:
  #     vlan_id: 5
  #     interfaces: 
  #       name: 
  #        - ethernet 1/1/40
  #     stp:
  #       type: 802-1w
  #       enabled: True
  #       priority: 20
  #     state: present

  # - name: enable rstp
  #   icx_vlan:
  #     vlan_id: 5
  #     stp:
  #         type: rstp
  #         enabled: True

  #test1
  # - name: check intent parameter for ports
  #   icx_vlan:
  #     vlan_id: 3
  #     check_running_config: True
  #     associated_interfaces: 
  #       - ethernet 1/1/1 to 1/1/2
  #       - ethernet 1/1/3
        

  # - name: check intent parameter for lag
  #   icx_vlan:
  #     vlan_id: 3
  #     associated_tagged: 
  #        - lag 1/1/11 to 1/1/12
  
  # test2
  # - name: check aggregate
  #   icx_vlan:
  #    aggregate:
  #    - {vlan_id: 6, name: vlan_6, tagged: { name: [ethernet 1/1/44]}, associated_tagged: ethernet 1/1/44 }
  #    - {vlan_id: 7, name: vlan_7, interfaces: {name: [ethernet 1/1/43]}, ip_dhcp_snooping: true}
  #    - {vlan_id: 8, name: vlan_8, tagged: {name: [ethernet 1/1/46 to 1/1/47]}, ip_arp_inspection: true}
  #    stp:
  #       type: 802-1w
  #       priority: 5
        

  # - name: purge parameter
  #   icx_vlan:
  #   #  vlan_id: 3
  #    aggregate:
  #    - { vlan_id: 3}
  #    - { vlan_id: 5}
  #   #  - {vlan_id: 21}
  #    purge: True

    register: result
  
  - debug:
     msg: '{{ result }}'
        
